server:
  port: 8002
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl 
    #cache-enabled: true   #开启MyBatis的二级缓存
  type-aliases-package: com.springcloud    # 所有Entity别名类所在包
  mapper-locations: classpath*:com/springcloud/mapper/**/*.xml    # mapper映射文件所在路径
  #mapper-locations: classpath*:mybatis/mapper/**/*.xml

#mybatis 日志输出，其中mapper映射文件（写SQL语句的接口）的包名为：com.springcloud.mapper
#logging: 
#  level: 
#    com: 
#    springcloud: 
#        mapper: DEBUG


eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      #defaultZone: http://localhost:7021/eureka #这个是单个eureka的时候配置
      defaultZone: http://eureka7021.com:7021/eureka/,http://eureka7022.com:7022/eureka/,http://eureka7023.com:7023/eureka/   #eureka集群配置
      
  instance: 
    instance-id: provider-dept-8002  #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
    
 
   
spring:
   application:
    name: provider-dept-8002
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb02?useSSL=false              # 数据库名称
    username: root
    password: dyc1214
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

info:
  app.name: springcloud
  company.name: www.dycspringcloud.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
