server:
  port: 8001
  
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.springcloud    # 所有Entity别名类所在包
  mapper-locations: classpath*:com/springcloud/mapper/**/*.xml                       # mapper映射文件
  #mapper-locations: classpath*:mybatis/mapper/**/*.xml

#mybatis 日志输出，其中mapper映射文件（写SQL语句的接口）的包名为：com.springcloud.mapper
#logging: 
#  level: 
#    com: 
#      springcloud: 
#        mapper: DEBUG


   
spring:
   application:
    name: microservicecloud-dept 
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: org.gjt.mm.mysql.Driver              # mysql驱动包
    url: jdbc:mysql://localhost:3306/clouddb01?useSSL=false              # 数据库名称
    username: root
    password: dyc1214
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

    
